name: Build Flatpak Repository

on:
  # push:
  #   branches: ["main"]
  
  workflow_dispatch:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/gnome:45
      options: --privileged
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Install org.freedesktop.Platform
        run: flatpak install --noninteractive flathub org.freedesktop.Platform//23.08

      - name: Install org.freedesktop.Sdk
        run: flatpak install --noninteractive flathub org.freedesktop.Sdk//23.08

      - name: Install org.freedesktop.Sdk.Extension.llvm17
        run: flatpak install --noninteractive flathub org.freedesktop.Sdk.Extension.llvm17//23.08

      - name: Install org.freedesktop.Sdk.Extension.rust-stable
        run: flatpak install --noninteractive flathub org.freedesktop.Sdk.Extension.rust-stable//23.08

      - name: Build Core App
        id: build
        uses: andyholmes/flatter@main
        with:
          files: |
            build-aux/org.espeak.Speech.Provider.json
          arch: x86_64
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}

      - name: Setup Flatpak
        run: |
          flatpak remote-add --no-gpg-verify --if-not-exists \
                  espeak-repo ${{steps.build.outputs.repository}}

      - name: Build Extensions
        id: build-ext
        uses: andyholmes/flatter@main
        with:
          files: |
            build-aux/voices/org.espeak.Speech.Provider.Voice.adam.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Alex.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Alicia.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Andrea.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Andy.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.anika.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.anikaRobot.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Annie.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.announcer.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.antonio.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.AnxiousAndy.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.aunty.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.belinda.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.benjamin.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.boris.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.caleb.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.croak.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.david.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Demonic.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Denis.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Diogo.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.ed.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.edward2.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.edward.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.f1.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.f2.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.f3.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.f4.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.f5.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.fast.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Gene2.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Gene.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.grandma.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.grandpa.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.gustave.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Henrique.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Hugo.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.iven2.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.iven3.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.iven4.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.iven.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Jacky.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.john.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.kaukovalta.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.klatt2.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.klatt3.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.klatt4.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.klatt5.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.klatt6.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.klatt.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Lee.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.linda.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.m1.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.m2.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.m3.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.m4.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.m5.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.m6.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.m7.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.m8.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.marcelo.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Marco.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Mario.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.max.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Michael.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.michel.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.miguel.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Mike.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Mr_serious.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Nguyen.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.norbert.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.pablo.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.paul.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.pedro.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.quincy.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.RicishayMax2.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.RicishayMax3.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.RicishayMax.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.robert.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.rob.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.robosoft2.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.robosoft3.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.robosoft4.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.robosoft5.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.robosoft6.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.robosoft7.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.robosoft8.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.robosoft.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.sandro.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.shelby.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.steph2.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.steph3.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.steph.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Storm.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.travis.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.Tweaky.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.UniRobot.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.victor.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.whisperf.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.whisper.json
            build-aux/voices/org.espeak.Speech.Provider.Voice.zac.json
          arch: x86_64
          flatpak-builder-args: |
            --install-deps-from=espeak-repo
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: ${{ steps.build.outputs.repository }}
          target-folder: repo
          single-commit: true
        