name: Build Flatpak Repository

on:
  # push:
  #   branches: ["main"]
  
  workflow_dispatch:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/gnome:45
      options: --privileged
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Install org.freedesktop.Platform
        run: flatpak install --noninteractive flathub org.freedesktop.Platform//23.08

      - name: Install org.freedesktop.Sdk
        run: flatpak install --noninteractive flathub org.freedesktop.Sdk//23.08

      - name: Install org.freedesktop.Sdk.Extension.llvm17
        run: flatpak install --noninteractive flathub org.freedesktop.Sdk.Extension.llvm17//23.08

      - name: Install org.freedesktop.Sdk.Extension.rust-stable
        run: flatpak install --noninteractive flathub org.freedesktop.Sdk.Extension.rust-stable//23.08

      - name: Build Core App
        id: build
        uses: andyholmes/flatter@main
        with:
          files: |
            build-aux/org.espeak.Speech.Provider.json
          arch: x86_64
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}

      - name: Setup Flatpak
        run: |
          flatpak remote-add --no-gpg-verify --if-not-exists \
                  espeak-repo ${{steps.build.outputs.repository}}

      - name: Build Extensions
        id: build-ext
        uses: andyholmes/flatter@main
        with:
          files: |
            build-aux/voices/org.espeak.Speech.Provider.Voice.Alex.json
          arch: x86_64
          flatpak-builder-args: |
            --install-deps-from=espeak-repo
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: ${{ steps.build.outputs.repository }}
          target-folder: repo
          single-commit: true
        