name: Build Flatpak Repository

on:
  # push:
  #   branches: ["main"]
  
  workflow_dispatch:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/gnome:45
      options: --privileged
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Install org.freedesktop.Platform
        run: flatpak install --noninteractive flathub org.freedesktop.Platform//23.08

      - name: Install org.freedesktop.Sdk
        run: flatpak install --noninteractive flathub org.freedesktop.Sdk//23.08

      - name: Install org.freedesktop.Sdk.Extension.llvm17
        run: flatpak install --noninteractive flathub org.freedesktop.Sdk.Extension.llvm17//23.08

      - name: Install org.freedesktop.Sdk.Extension.rust-stable
        run: flatpak install --noninteractive flathub org.freedesktop.Sdk.Extension.rust-stable//23.08

      - name: Build Core App
        id: build
        uses: andyholmes/flatter@main
        with:
          files: |
            build-aux/org.espeak.Speech.Provider.json
          arch: x86_64
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}

      - name: Setup Flatpak
        run: |
          flatpak remote-add --no-gpg-verify --if-not-exists \
                  espeak-repo ${{steps.build.outputs.repository}}

      - name: Build Extensions
        id: build-ext
        uses: andyholmes/flatter@main
        with:
          files: |
            org.espeak.Speech.Provider.Voice.adam.json
            org.espeak.Speech.Provider.Voice.Alex.json
            org.espeak.Speech.Provider.Voice.Alicia.json
            org.espeak.Speech.Provider.Voice.Andrea.json
            org.espeak.Speech.Provider.Voice.Andy.json
            org.espeak.Speech.Provider.Voice.anika.json
            org.espeak.Speech.Provider.Voice.anikaRobot.json
            org.espeak.Speech.Provider.Voice.Annie.json
            org.espeak.Speech.Provider.Voice.announcer.json
            org.espeak.Speech.Provider.Voice.antonio.json
            org.espeak.Speech.Provider.Voice.AnxiousAndy.json
            org.espeak.Speech.Provider.Voice.aunty.json
            org.espeak.Speech.Provider.Voice.belinda.json
            org.espeak.Speech.Provider.Voice.benjamin.json
            org.espeak.Speech.Provider.Voice.boris.json
            org.espeak.Speech.Provider.Voice.caleb.json
            org.espeak.Speech.Provider.Voice.croak.json
            org.espeak.Speech.Provider.Voice.david.json
            org.espeak.Speech.Provider.Voice.Demonic.json
            org.espeak.Speech.Provider.Voice.Denis.json
            org.espeak.Speech.Provider.Voice.Diogo.json
            org.espeak.Speech.Provider.Voice.ed.json
            org.espeak.Speech.Provider.Voice.edward2.json
            org.espeak.Speech.Provider.Voice.edward.json
            org.espeak.Speech.Provider.Voice.f1.json
            org.espeak.Speech.Provider.Voice.f2.json
            org.espeak.Speech.Provider.Voice.f3.json
            org.espeak.Speech.Provider.Voice.f4.json
            org.espeak.Speech.Provider.Voice.f5.json
            org.espeak.Speech.Provider.Voice.fast.json
            org.espeak.Speech.Provider.Voice.Gene2.json
            org.espeak.Speech.Provider.Voice.Gene.json
            org.espeak.Speech.Provider.Voice.grandma.json
            org.espeak.Speech.Provider.Voice.grandpa.json
            org.espeak.Speech.Provider.Voice.gustave.json
            org.espeak.Speech.Provider.Voice.Henrique.json
            org.espeak.Speech.Provider.Voice.Hugo.json
            org.espeak.Speech.Provider.Voice.iven2.json
            org.espeak.Speech.Provider.Voice.iven3.json
            org.espeak.Speech.Provider.Voice.iven4.json
            org.espeak.Speech.Provider.Voice.iven.json
            org.espeak.Speech.Provider.Voice.Jacky.json
            org.espeak.Speech.Provider.Voice.john.json
            org.espeak.Speech.Provider.Voice.kaukovalta.json
            org.espeak.Speech.Provider.Voice.klatt2.json
            org.espeak.Speech.Provider.Voice.klatt3.json
            org.espeak.Speech.Provider.Voice.klatt4.json
            org.espeak.Speech.Provider.Voice.klatt5.json
            org.espeak.Speech.Provider.Voice.klatt6.json
            org.espeak.Speech.Provider.Voice.klatt.json
            org.espeak.Speech.Provider.Voice.Lee.json
            org.espeak.Speech.Provider.Voice.linda.json
            org.espeak.Speech.Provider.Voice.m1.json
            org.espeak.Speech.Provider.Voice.m2.json
            org.espeak.Speech.Provider.Voice.m3.json
            org.espeak.Speech.Provider.Voice.m4.json
            org.espeak.Speech.Provider.Voice.m5.json
            org.espeak.Speech.Provider.Voice.m6.json
            org.espeak.Speech.Provider.Voice.m7.json
            org.espeak.Speech.Provider.Voice.m8.json
            org.espeak.Speech.Provider.Voice.marcelo.json
            org.espeak.Speech.Provider.Voice.Marco.json
            org.espeak.Speech.Provider.Voice.Mario.json
            org.espeak.Speech.Provider.Voice.max.json
            org.espeak.Speech.Provider.Voice.Michael.json
            org.espeak.Speech.Provider.Voice.michel.json
            org.espeak.Speech.Provider.Voice.miguel.json
            org.espeak.Speech.Provider.Voice.Mike.json
            org.espeak.Speech.Provider.Voice.Mr_serious.json
            org.espeak.Speech.Provider.Voice.Nguyen.json
            org.espeak.Speech.Provider.Voice.norbert.json
            org.espeak.Speech.Provider.Voice.pablo.json
            org.espeak.Speech.Provider.Voice.paul.json
            org.espeak.Speech.Provider.Voice.pedro.json
            org.espeak.Speech.Provider.Voice.quincy.json
            org.espeak.Speech.Provider.Voice.RicishayMax2.json
            org.espeak.Speech.Provider.Voice.RicishayMax3.json
            org.espeak.Speech.Provider.Voice.RicishayMax.json
            org.espeak.Speech.Provider.Voice.robert.json
            org.espeak.Speech.Provider.Voice.rob.json
            org.espeak.Speech.Provider.Voice.robosoft2.json
            org.espeak.Speech.Provider.Voice.robosoft3.json
            org.espeak.Speech.Provider.Voice.robosoft4.json
            org.espeak.Speech.Provider.Voice.robosoft5.json
            org.espeak.Speech.Provider.Voice.robosoft6.json
            org.espeak.Speech.Provider.Voice.robosoft7.json
            org.espeak.Speech.Provider.Voice.robosoft8.json
            org.espeak.Speech.Provider.Voice.robosoft.json
            org.espeak.Speech.Provider.Voice.sandro.json
            org.espeak.Speech.Provider.Voice.shelby.json
            org.espeak.Speech.Provider.Voice.steph2.json
            org.espeak.Speech.Provider.Voice.steph3.json
            org.espeak.Speech.Provider.Voice.steph.json
            org.espeak.Speech.Provider.Voice.Storm.json
            org.espeak.Speech.Provider.Voice.travis.json
            org.espeak.Speech.Provider.Voice.Tweaky.json
            org.espeak.Speech.Provider.Voice.UniRobot.json
            org.espeak.Speech.Provider.Voice.victor.json
            org.espeak.Speech.Provider.Voice.whisperf.json
            org.espeak.Speech.Provider.Voice.whisper.json
            org.espeak.Speech.Provider.Voice.zac.json
          arch: x86_64
          flatpak-builder-args: |
            --install-deps-from=espeak-repo
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: ${{ steps.build.outputs.repository }}
          target-folder: repo
          single-commit: true
        